# Funding options for this project
# Uncomment and configure as needed

# github: [username]
# patreon: username
# open_collective: project-name
# ko_fi: username
# custom: ["https://example.com/donate"]
