#!/usr/bin/env bash
# scripts/vps/install-lifecycle-guard.sh
#
# Make the ADR-025 lifecycle write guard actually run, in every project the
# orchestrator touches — including the ones that never received DLD's
# .git-hooks/ + .claude/hooks/ files.
#
# WHY THIS EXISTS (audited 2026-07-27, 10 projects):
#   Only gipotenuza and wb had ANY executable pre-commit hook, and wb's
#   core.hooksPath was relative (`.git-hooks`), which resolves against
#   .git/worktrees/<name>/ inside a worktree — i.e. dead exactly where autopilot
#   runs. dld, dowry and wb carried the wrapper at .git-hooks/pre-commit but
#   pointed core.hooksPath at .git/hooks, so the wrapper was never invoked.
#   dowry-mc, nexus, plpilot, gipotenuza, memyselfandi and mishkinlyap carried
#   neither the wrapper nor the guard. Net effect: the structural half of
#   ADR-025 was deployed nowhere, and autopilot was observed writing
#   ai/lifecycle/*.yaml straight into a working tree.
#
#   install-hooks-all-worktrees.sh cannot fix this — it only rewrites
#   core.hooksPath and SKIPs any project without a checked-in .git-hooks/
#   directory, which is six of the ten.
#
# WHAT IT DOES
#   Installs ONE shared wrapper outside every repo and points core.hooksPath at
#   it. The wrapper resolves the guard from the repo first and falls back to
#   DLD's copy, so a project needs no files of its own. It then chains to the
#   repo's pre-existing pre-commit hook (husky, .git/hooks) when that hook is
#   executable, so nothing already in place is silently disabled.
#
# Usage:
#   bash install-lifecycle-guard.sh            # install (idempotent)
#   bash install-lifecycle-guard.sh --dry-run  # show what would change
#   bash install-lifecycle-guard.sh --verify   # report effective state only
#
# Env:
#   PROJECTS_JSON  path to projects.json (default: alongside this script)
#   DLD_HOOKS_DIR  where the shared wrapper lands (default: $HOME/.dld-hooks)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECTS_FILE="${PROJECTS_JSON:-${SCRIPT_DIR}/projects.json}"
HOOKS_DIR="${DLD_HOOKS_DIR:-${HOME}/.dld-hooks}"
CENTRAL_GUARD="$(cd "${SCRIPT_DIR}/../.." && pwd)/.claude/hooks/pre-commit-lifecycle-guard.mjs"

MODE="install"
case "${1:-}" in
    --dry-run) MODE="dry-run" ;;
    --verify)  MODE="verify" ;;
    "")        ;;
    *) echo "unknown argument: $1 (use --dry-run or --verify)" >&2; exit 2 ;;
esac

if ! command -v jq >/dev/null 2>&1; then
    echo "ERROR: jq required (apt install jq)" >&2
    exit 1
fi
if [[ ! -f "$PROJECTS_FILE" ]]; then
    echo "ERROR: projects.json not found at $PROJECTS_FILE" >&2
    exit 1
fi
if [[ ! -f "$CENTRAL_GUARD" ]]; then
    echo "ERROR: central guard missing at $CENTRAL_GUARD" >&2
    exit 1
fi

write_wrapper() {
    mkdir -p "$HOOKS_DIR"
    cat > "${HOOKS_DIR}/pre-commit" <<WRAPPER
#!/usr/bin/env bash
# GENERATED by scripts/vps/install-lifecycle-guard.sh — do not edit in place.
#
# Shared pre-commit for every DLD-orchestrated repo:
#   1. ADR-025 lifecycle write guard (repo-local copy, else DLD's central copy)
#   2. chain to whatever pre-commit the repo already had, if it was executable
set -uo pipefail

_common_dir=\$(git rev-parse --git-common-dir 2>/dev/null || echo ".git")
case "\$_common_dir" in
    /*) _repo_root="\$(dirname "\$_common_dir")" ;;
    *)  _repo_root="\$(git rev-parse --show-toplevel 2>/dev/null || pwd)" ;;
esac

_guard="\${_repo_root}/.claude/hooks/pre-commit-lifecycle-guard.mjs"
[[ -f "\$_guard" ]] || _guard="\${DLD_LIFECYCLE_GUARD:-${CENTRAL_GUARD}}"

if [[ -f "\$_guard" ]] && command -v node >/dev/null 2>&1; then
    node "\$_guard" || exit 1
else
    # Fail OPEN for ordinary commits (a missing guard must not block all work),
    # fail CLOSED for the only commits the guard exists to stop. TECH-194 called
    # blanket fail-open a defect; blanket fail-closed would wedge every repo on a
    # missing node. This splits the difference at the precise boundary.
    if git diff --cached --name-only --diff-filter=ACMR 2>/dev/null \\
        | grep -Eq '^ai/lifecycle/[^/]+\.yaml\$'; then
        echo "pre-commit: staged ai/lifecycle/ but the lifecycle guard is unavailable" >&2
        echo "  looked for: \$_guard  (node: \$(command -v node || echo MISSING))" >&2
        echo "  lifecycle is written by callback only — see ADR-023 / ADR-025" >&2
        exit 1
    fi
fi

# Chain: run the repo's own pre-commit if it exists and git would have run it.
# Skip any file that is itself a lifecycle-guard wrapper (already covered above).
for _candidate in "\${_repo_root}/.husky/pre-commit" "\${_repo_root}/.git/hooks/pre-commit" "\${_repo_root}/.git-hooks/pre-commit"; do
    [[ -x "\$_candidate" ]] || continue
    grep -q "pre-commit-lifecycle-guard" "\$_candidate" 2>/dev/null && continue
    "\$_candidate" "\$@" || exit \$?
    break
done

exit 0
WRAPPER
    chmod +x "${HOOKS_DIR}/pre-commit"
}

# Effective hook = the file git would actually execute for this repo.
effective_hook() {
    local repo="$1" hp
    hp=$(git -C "$repo" config core.hooksPath 2>/dev/null || echo "")
    if [[ -z "$hp" ]]; then
        echo "${repo}/.git/hooks/pre-commit"
    elif [[ "$hp" == /* ]]; then
        echo "${hp}/pre-commit"
    else
        echo "${repo}/${hp}/pre-commit"   # relative: broken inside worktrees
    fi
}

guard_reachable() {
    local repo="$1"
    [[ -f "${repo}/.claude/hooks/pre-commit-lifecycle-guard.mjs" ]] && return 0
    [[ -f "$CENTRAL_GUARD" ]] && return 0
    return 1
}

if [[ "$MODE" != "verify" ]]; then
    if [[ "$MODE" == "dry-run" ]]; then
        echo "[dry-run] would write ${HOOKS_DIR}/pre-commit (guard: ${CENTRAL_GUARD})"
    else
        write_wrapper
        echo "[OK]   shared wrapper: ${HOOKS_DIR}/pre-commit"
        echo "[OK]   central guard:  ${CENTRAL_GUARD}"
    fi

    while IFS= read -r proj; do
        [[ -z "$proj" ]] && continue
        name=$(basename "$proj")
        if [[ ! -d "${proj}/.git" && ! -f "${proj}/.git" ]]; then
            echo "[SKIP] ${name}: not a git repo"
            continue
        fi
        current=$(git -C "$proj" config core.hooksPath 2>/dev/null || echo "")
        if [[ "$current" == "$HOOKS_DIR" ]]; then
            echo "[OK]   ${name}: already on shared hooks"
            continue
        fi
        if [[ "$MODE" == "dry-run" ]]; then
            echo "[dry-run] ${name}: core.hooksPath ${current:-<unset>} -> ${HOOKS_DIR}"
            continue
        fi
        # Remember what was there so the change is reversible without guesswork.
        if [[ -n "$current" ]]; then
            git -C "$proj" config dld.previousHooksPath "$current"
        fi
        git -C "$proj" config core.hooksPath "$HOOKS_DIR"
        echo "[FIX]  ${name}: core.hooksPath=${HOOKS_DIR} (was: ${current:-<unset>})"
    done < <(jq -r '.[].path' "$PROJECTS_FILE")
fi

echo
printf "%-14s %-8s %-8s %s\n" PROJECT GUARD CHAINED "effective pre-commit"
while IFS= read -r proj; do
    [[ -z "$proj" ]] && continue
    name=$(basename "$proj")
    hook=$(effective_hook "$proj")
    if [[ -x "$hook" ]]; then
        if guard_reachable "$proj"; then state="ACTIVE"; else state="NOGUARD"; fi
    else
        state="ABSENT"
    fi
    chained="-"
    for c in "${proj}/.husky/pre-commit" "${proj}/.git/hooks/pre-commit" "${proj}/.git-hooks/pre-commit"; do
        [[ -x "$c" ]] || continue
        grep -q "pre-commit-lifecycle-guard" "$c" 2>/dev/null && continue
        chained="$(basename "$(dirname "$c")")"
        break
    done
    printf "%-14s %-8s %-8s %s\n" "$name" "$state" "$chained" "$hook"
done < <(jq -r '.[].path' "$PROJECTS_FILE")
